# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["uhci_hcd" "ehci_pci" "ata_piix" "ahci" "pata_jmicron" "xhci_pci" "firewire_ohci" "usbhid" "usb_storage" "floppy" "sd_mod"];
  boot.initrd.kernelModules = ["dm-snapshot"];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/d4be8cf2-5a52-40f1-ac9d-ceffeefbadf3";
    fsType = "btrfs";
    options = ["subvol=@,compress=zstd"];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/361f8036-6466-41e9-ba19-9f6bda36993f";
    fsType = "btrfs";
  };

  swapDevices = [
    {device = "/dev/disk/by-uuid/98f0eb16-59bc-42ff-929d-5e468d4c08e0";}
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp2s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp5s1.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp5s4.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp0s26f7u3.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
