[hosts.kirby]
ip_address = "192.168.5.50"
tailscale_address = "100.108.110.99"

[hosts.yoshi]
ip_address = "192.168.5.40"
syncthing_id = "JWHC7VW-IBHY6KB-6AHKCBS-3Q6J4ID-R57YAWM-7ZRMWGR-F2YRGHB-F7JHTAN"

[hosts.nixos-2022-desktop]
ip_address = "192.168.4.32"
syncthing_id = "4JP4C67-VSQX646-E4BRJDC-ZQ2ZTNJ-CKWNUSS-2FC46OK-MDN7DB7-JCKBXQW"

# Framework Laptop
[hosts.fwnixos]
syncthing_id = "DQ5PQ5T-OEQQGJ5-C67RF4Y-SJR5NIZ-WPFSJQT-YNXFOET-37356WL-P7LWNQH"

[hosts.pixel4a]
syncthing_id = "NPVNVC5-J2CKZF6-6LUH6NF-3NYG6GP-GUERNAO-O35UZUC-L6ADKSK-SPRA3AL"
