[hosts.kirby]
ip_address = "192.168.5.50"
tailscale_address = "100.64.5.50"

[hosts.yoshi]
ip_address = "192.168.5.40"
tailscale_address = "100.64.5.40"
syncthing_id = "JWHC7VW-IBHY6KB-6AHKCBS-3Q6J4ID-R57YAWM-7ZRMWGR-F2YRGHB-F7JHTAN"

# Desktop PC - Z390 Core i7-9700K (2019)
[hosts.nixos-2022-desktop]
ip_address = "192.168.4.32"
syncthing_id = "4JP4C67-VSQX646-E4BRJDC-ZQ2ZTNJ-CKWNUSS-2FC46OK-MDN7DB7-JCKBXQW"

# Framework Laptop
[hosts.fwnixos]
ip_address = "192.168.5.64"
syncthing_id = "DQ5PQ5T-OEQQGJ5-C67RF4Y-SJR5NIZ-WPFSJQT-YNXFOET-37356WL-P7LWNQH"

[hosts.lakitu]
ip_address = "192.168.10.10"
tailscale_address = "100.64.10.10"
description = "Router - Dell OptiPlex 5080 SFF - Intel Core i5-10500 (purchased 2023)"

[hosts.pixel4a]
syncthing_id = "NPVNVC5-J2CKZF6-6LUH6NF-3NYG6GP-GUERNAO-O35UZUC-L6ADKSK-SPRA3AL"

[hosts.pixel8]
syncthing_id = "GBWH2AC-3CFVNM2-ZREH43F-B6FROI3-U7ADLWP-OWNIWVK-BNPBUQ5-EH7HAQ5"

# Work Laptop - Dell Latitude 5530 (2023)
[hosts.work-laptop]
syncthing_id = "ME2B765-2HQWLAO-A7PRWE3-RP44QKE-UIJTZSH-467P3GF-JE7FSWY-ZYCPQQA"

# VFIO VM (Windows) - maybe a Samba shared folder would be better, to
# avoid having to run Syncthing in the VM.
# Linux VFIO VMs can use a 9p shared folder from the host.
[hosts.vfio-windows]
syncthing_id = "CNJBSUE-KIERN7M-6WKA2YC-OO4EDQB-FKM2YJT-HZIOYOF-WKQ6NPJ-CEAHJAU"

[vms.homeassistant]
# In the libvirt 'default' NAT network. Home Assistant is configured to use
# a static IP address at https://my.home-assistant.io/redirect/network/.
internal_ip = "192.168.122.64"

[vms.stalfos]
internal_ip = "192.168.122.30"

# Keep a list of UIDs and GIDs in one place to avoid creating conflicts.
[uids]
scanner = 20010
homeassistant = 20020
nextcloud = 20030

[gids]
inbox = 20000 # Group for scanner
storage = 20010 # Allow access to /storage
homeassistant = 20020
nextcloud = 20030
multimedia = 20050
calibre = 20060
